"""permisos rol_permiso usuario_permiso y columnas roles usuarios step1

Revision ID: a4c461ccb017
Revises: 
Create Date: 2026-09-09 18:41:18.396777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c461ccb017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=4095), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permisos'))
    )
    op.create_index(op.f('ix_permisos_nombre'), 'permisos', ['nombre'], unique=True)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name=op.f('fk_rol_permiso_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], name=op.f('fk_rol_permiso_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name=op.f('pk_rol_permiso'))
    )
    op.create_index(op.f('ix_rol_permiso_permiso_id'), 'rol_permiso', ['permiso_id'], unique=False)
    op.create_table('usuario_permiso',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name=op.f('fk_usuario_permiso_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], name=op.f('fk_usuario_permiso_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'permiso_id', name=op.f('pk_usuario_permiso'))
    )
    op.create_index(op.f('ix_usuario_permiso_permiso_id'), 'usuario_permiso', ['permiso_id'], unique=False)
    op.add_column('roles', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ultima_conexion')
    op.drop_column('roles', 'fecha_creacion')
    op.drop_column('roles', 'descripcion')
    op.drop_index(op.f('ix_usuario_permiso_permiso_id'), table_name='usuario_permiso')
    op.drop_table('usuario_permiso')
    op.drop_index(op.f('ix_rol_permiso_permiso_id'), table_name='rol_permiso')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_permisos_nombre'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
