"""empresas y sucursales CU16 nit email ciudad

Revision ID: 816f55fba873
Revises: b7d5f0e2c4a9
Create Date: 2026-09-10 07:54:19.706978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816f55fba873'
down_revision: Union[str, Sequence[str], None] = 'b7d5f0e2c4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas'))
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_sucursales_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sucursales')),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_sucursal_empresa_nombre')
    )
    op.create_index(op.f('ix_sucursales_empresa_id'), 'sucursales', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_index(op.f('ix_sucursales_empresa_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
