"""crear_tablas_carrito_items_cu15

Revision ID: b7ade8af60d1
Revises: f7b2c3d4e5a6
Create Date: 2026-09-20 19:20:49.156216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ade8af60d1'
down_revision: Union[str, Sequence[str], None] = 'f7b2c3d4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carritos',
    sa.Column('id_carrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('fk_carritos_id_usuario_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carrito', name=op.f('pk_carritos'))
    )
    op.create_index(op.f('ix_carritos_id_carrito'), 'carritos', ['id_carrito'], unique=False)
    op.create_index(op.f('ix_carritos_id_usuario'), 'carritos', ['id_usuario'], unique=True)
    op.create_table('items_carrito',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('id_sucursal_preferida', sa.Integer(), nullable=True),
    sa.Column('fecha_agregado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_items_carrito_cantidad_item_carrito_positiva')),
    sa.ForeignKeyConstraint(['id_carrito'], ['carritos.id_carrito'], name=op.f('fk_items_carrito_id_carrito_carritos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('fk_items_carrito_id_producto_productos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sucursal_preferida'], ['sucursales.codigo_sucursal'], name=op.f('fk_items_carrito_id_sucursal_preferida_sucursales'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_item', name=op.f('pk_items_carrito')),
    sa.UniqueConstraint('id_carrito', 'id_producto', 'talla', 'color', name='uq_item_carrito_variante')
    )
    op.create_index(op.f('ix_items_carrito_id_carrito'), 'items_carrito', ['id_carrito'], unique=False)
    op.create_index(op.f('ix_items_carrito_id_item'), 'items_carrito', ['id_item'], unique=False)
    op.create_index(op.f('ix_items_carrito_id_producto'), 'items_carrito', ['id_producto'], unique=False)
    op.create_index(op.f('ix_items_carrito_id_sucursal_preferida'), 'items_carrito', ['id_sucursal_preferida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_items_carrito_id_sucursal_preferida'), table_name='items_carrito')
    op.drop_index(op.f('ix_items_carrito_id_producto'), table_name='items_carrito')
    op.drop_index(op.f('ix_items_carrito_id_item'), table_name='items_carrito')
    op.drop_index(op.f('ix_items_carrito_id_carrito'), table_name='items_carrito')
    op.drop_table('items_carrito')
    op.drop_index(op.f('ix_carritos_id_usuario'), table_name='carritos')
    op.drop_index(op.f('ix_carritos_id_carrito'), table_name='carritos')
    op.drop_table('carritos')

    # ### end Alembic commands ###
